### ISSUE TITLE
Xcode Version 6.3.2 (6D2105) -> doesn't work

### ISSUE THREAD

**Issue by kladis** [flexih/Xcode-CComment#2]
Hello,

First, thanks you for this great plug-in!

I have now some difficulties with it: shortcuts doesn't work. I am not sure also if this plugin was "plugged in" really, this is "Edit" menu: http://gyazo.com/f391fb00d249f5d58425e28ff8013fb4

But dir ~/Library/... contains this plugin, and the "Alcatraz.xcplugin" can install and un-install this plugin.

Would be great to repair :)

Thanks!

**Comment by flexih** [comment]
Thanks for your report. Fixed.
