### ISSUE TITLE
Comments with space either side

### ISSUE THREAD

**Issue by ianmasters** [flexih/Xcode-CComment#3]
Thanks for a nice little plugin. It's very handy.

I find it a bit annoying the the comments include a space character after and before the start and end comment. This means when you uncomment the space is left intact and you get an unwanted 2 space characters.

Could I suggest either:
- removing the space characters when commenting
- adding an option to enable/disable leading/trailing space within the comment, and if enabled remove the space characters along with the comment characters

thanks for any consideration

**Comment by flexih** [comment]
Actually, I prefer the previous comment style. No more change comment style until it can be configurable :-)

**Comment by ianmasters** [comment]
Thats the whole point of preferences isn't it? A preference?
We are not all the same.
I mean I've hacked your code to do what I require in short time, for my purposes, but it needs to be configurable if you want it to be successful. At least if you pad the comments with spaces, remove the spaces when you un-comment! or you have a discontinuity.

**Comment by flexih** [comment]
Hi, I create a new branch "setting". I add a config option, and solve the bug.

**Comment by ianmasters** [comment]
Excellent work. Thank you! (options are good!)
