### ISSUE TITLE
Doesn't work on Xcode 6.4

### ISSUE THREAD

**Issue by mohpor** [flexih/Xcode-CComment#4]
Hi, I'm more than addicted to this plug in, and it simply stopped working after upgrading to Xcode 6.4.

Here are what I've tried so far:

1- Uninstall/Reinstall from alcatraz
2- Uninstall from alcatraz, build using Xcode
3- Delete plugin file from plugins folder

Here is what I know:

You know that annoying `Load Bundles` alert thingie before Xcode launch? That appears and it just so happens that checking allowed/skipped plugins returns no trace of CComment at all!

here is how I check:

```
defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4
```

The returned value doesn't include CComment. After witnessing this odd behavior I tried to remedy as good as I could so, what I did was:

```
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4
```

to remove plugin permissions from defaults,  checked inside `CComment.xcplugin` to see if the appropriate UUID is available under `DVTPlugInCompatibilityUUIDs` in your `info.plist`, restarted Xcode, clicked on Load Bundles, double checked the PlugIns permissions, and there still is no trace of CComent!

What can I do now?

**Comment by flexih** [comment]
Fixed. Please update.
BTW: I add how to fix to README.

**Comment by mohpor** [comment]
tnx
