### ISSUE TITLE
how to customise my short-cut

### ISSUE THREAD

**Issue by benjaminwhx** [flexih/Xcode-CComment#7]
as title.by the way,你在腾讯也在北京吗？

**Comment by flexih** [comment]
是的。目前只能修改代码来更改快捷键。

**Comment by benjaminwhx** [comment]
是修改哪里的代码呢？我想把快捷键改成shift+cmd+/

**Comment by flexih** [comment]
CComment.m line74
[actionMenuItem setKeyEquivalentModifierMask:NSControlKeyMask | NSCommandKeyMask];
修改为
[actionMenuItem setKeyEquivalentModifierMask:NSShiftKeyMask | NSCommandKeyMask];

**Comment by benjaminwhx** [comment]
thankyou，我想从java转型ios了，目前在学c和objective-c，能加个qq吗以后有问题想问问大神。449261417

**Comment by flexih** [comment]
我不是大神。。。可以加下微博http://weibo.com/flexih :)
