### ISSUE TITLE
Doesn't work with Xcode 7 :(

### ISSUE THREAD

**Issue by nikitaUnii** [flexih/Xcode-CComment#8]

**Comment by nikitaUnii** [comment]
Thanks for this plugin.

I tried the method you have mentioned in Readme file. However, this does not fix it for me in Xcode 7. Would be a great help if you could tell me how can i fix otherwise :)

**Comment by flexih** [comment]
Hi, it works on Xcode 7. Just update to latest code and compile, or download latest CComment.xcplugin in bin directory and replace the old.

**Comment by flexih** [comment]
Hi, does it work?

**Comment by nikitaUnii** [comment]
Hey thanks..I forgot to restart the xcode - now it works :D
